### ISSUE TITLE
Draw multiple cubes using vulkan 

### ISSUE THREAD

**Issue by monica2203** [LunarG/VulkanSamples#147]
Hi, I was using the Vulcan API Samples for android and I modified the 15-draw-cube.cpp file at line#149 to draw multiple cubes and this doesn't work. Is it possible to draw multiple cubes in this way or should something else also be done.
`vkCmdDraw(info.cmd, 12 * 3, 1, 0, 0);
 vkCmdDraw(info.cmd, 12 * 3, 1, 2, 2);
vkCmdDraw(info.cmd, 12 * 3, 1, 4, 4);`

**Comment by karl-lunarg** [comment]
This isn't the way to draw multiple cubes.  The 4th argument (`firstVertex`) to `vkCmdDraw` is an offset into a vertex list (array) of vertices to draw.   It is not a "geometric" offset that you might use to scoot the cube over to the right along the X direction or anything like that.  Changing `firstVertex` to 4 just causes you to skip the first 4 vertices in the vertex list, which isn't what you want.

Simply repeating the call to `vkCmdDraw` will draw the cube twice; just in the same place, so you really can't tell if it drew twice.

The easiest way to do this is probably with instancing.

Change the `instanceCount` argument to 2, and the geometry will draw twice.  You'll have to change the vertex shader program to look at the instance ID (`gl_InstanceIndex`) and if it is 0, do nothing.  If the instance ID is 1, apply some sort of transform to the vertex to move it someplace else.  For example, add a constant to the X component.  You might do this by adding a line to the current vertex shader:

```
pos.x += gl_InstanceIndex * 0.2;
```

right before the line where `gl_Position` is calculated.  This will add 0.2 to the X coordinate for each successive instance.  This way, you can change `instanceCount` to whatever you want, and you'll get a string of cubes drawing in row off to the right.

There are other approaches.  For example, you can use push constants instead of the uniform var to set the mvp matrix.  For each cube you want to draw:

* Compute the mvp matrix
* Call `vkCmdPushConstants` with that matrix
* Call `vkCmdDraw`

This approach also requires some shader modifications.   You may want to look at the push constants sample in this repo to see how to do that.

**Comment by monica2203** [comment]
Thank you for the explanation, Karl
