### ISSUE TITLE
`init_device` in `utils_init.cpp` only creates a graphics queue, even though `info.graphics_queue_index` may not be the same as `info.presentation_queue_index`?

### ISSUE THREAD

**Issue by bzm3r** [LunarG/VulkanSamples#173]
See code for `init_device` here: https://github.com/LunarG/VulkanSamples/blob/master/API-Samples/utils/util_init.cpp#L216

However, in the `init_swapchain` sample, the tutorial talks about how the physical device may not have a queue family which supports both graphics and presentation to a specified surface, and thus two separate queue families (each supporting one of the required functions) will need to be created.

Yet, `init_device` only creates a single queue family (based on info.graphics_queue_family_index) rather than two?

**Comment by karl-lunarg** [comment]
The `init_queue_family_index` function, which is where the graphics queue index is obtained, has the following comment:
```
    /* This routine simply finds a graphics queue for a later vkCreateDevice,
     * without consideration for which queue family can present an image.
     * Do not use this if your intent is to present later in your sample,
     * instead use the init_connection, init_window, init_swapchain_extension,
     * init_device call sequence to get a graphics and present compatible queue
     * family
     */
```
Since many of the samples don't ever do a present, this function is used by these samples to take the simpler approach to get only a graphics queue.

The `15-draw_cube.cpp` sample does do a present and follows the advice in the above comment to call `init_swapchain_extension`, which does contain the logic needed to handle separate graphics and present queues.

Note that in order to determine if a queue supports present, a surface must first be created using platform-specific surface creation functions.  See the call to `vkGetPhysicalDeviceSurfaceSupportKHR` in `init_swapchain_extension`.  All this would add unneeded complexity to the first dozen or so samples, since none of them need a surface.   We needed to avoid this complexity while introducing other Vulkan topics in the samples appearing earlier in the sequence.

Since this deferral of handling separate queues to the samples that actually need them was intentional and appropriate, I'm going to go ahead and close this, hoping that the above explanation suffices.
