### ISSUE TITLE
Frame stutter when resizing window

### ISSUE THREAD

**Issue by jeremyong** [LunarG/VulkanSamples#274]
Nvidia GeForce RTX 2070
Linux 5.4.3
Nvidia driver 440.44-2

Both the linux kernel and nvidia driver are pretty recent (as of this week)

I was hoping to reference the samples as I've been having trouble getting a smooth resize with my implementations. It seems the samples also experience the same stutter and will eventually crash due to a device lost issue.

*edit* I'm having trouble reproducing the device loss issue now, but I'm still getting the stutter/blank screens during resize, so I'm amending the issue.

**Comment by Tony-LunarG** [comment]
I noticed an exchange on this on the khronosdevs.slack #vulkan channel.  Did you file an issue with Nvidia?

**Comment by jeremyong** [comment]
Hey, the best I can gather is that the claim is the app needs to respond to X11's request to resize the window in order to paint before the next swap. As I'm less familiar with the X11 protocol, I may need to defer to someone's expertise who knows more until I find time to research it myself.

**Comment by Tony-LunarG** [comment]
When I resize Hologram, the window goes dark until I stop the resize and then the rendering continues.  Is  that what you're seeing?

Resizing in general is an expensive operation and the X server sends dozens of XCB_CONFIGURE_NOTIFY events as the window resizes, each requiring the sample to tear down the swapchain, and create a new swapchain using the new window size.

One thing you can try is to turn off vertical sync.  That will cause the sample to use VK_PRESENT_MODE_IMMEDIATE_KHR instead of VK_PRESENT_MODE_FIFO_KHR and the resize looks smoother at the risk of seeing tearing in the rendering.

**Comment by Tony-LunarG** [comment]
I forgot to mention that you turn off vertical sync by running Hologram with "-b" on the command line.

**Comment by Tony-LunarG** [comment]
Not sure what more Hologram can do to smooth resize, so closing this issue. Re-open if you feel there's more to be addressed
