### ISSUE TITLE
CMAKE missing link directive

### ISSUE THREAD

**Issue by yousry** [LunarG/VulkanSamples#78]
The build script throws following error:

CmakeErrorLog:
...
File .../CheckSymbolExists.c:

```C
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

...

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /mnt/hdd/home/yousry/Dokumente/source/vulkan/VulkanSamples/build/CMakeFiles/CMakeTmp

...

Makefile:126: die Regel für Ziel „cmTC_b7b8b/fast“ scheiterte
make: *** [cmTC_b7b8b/fast] Fehler 2

...
```

Certainly building this test isn't a problem if all necessary libraries are linked:

$CC CheckSymbolExists.c -lpthread

BTW I got the same result with gcc 5.3.

**Comment by Tony-LunarG** [comment]
I think this is just the way CMake searches for the threads package, in this case pthreads.  A portion of my cmake output looks like:

-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE 

Comparing that to the stock CMake FindThreads.cmake file:

    CHECK_SYMBOL_EXISTS(pthread_create pthread.h CMAKE_HAVE_LIBC_CREATE)
      if(CMAKE_HAVE_LIBC_CREATE)
        set(CMAKE_THREAD_LIBS_INIT "")
        set(CMAKE_HAVE_THREADS_LIBRARY 1)
        set(Threads_FOUND TRUE)
      else()

        # Check for -pthread first if enabled. This is the recommended
        # way, but not backwards compatible as one must also pass -pthread
        # as compiler flag then.
        if (THREADS_PREFER_PTHREAD_FLAG)
           _check_pthreads_flag()
        endif ()

It looks to me like it looks for the pthread_create symbol in the default standard library, doing so by trying to compile the program and failing to link.  Of course it doesn't find it there, so it takes the  else path of trying -pthread with the compiler and finding it there, satisfying its need for pthread.  The first check fails, and that's what we see in the log, but that's ok because the second check succeeded and pthreads is there.

**Comment by Tony-LunarG** [comment]
I believe CMake is working as expected - closing
