### ISSUE TITLE
"CMAKE_CXX_COMPILER-NOTFOUND" was not found. in vs2015

### ISSUE THREAD

**Issue by jettangs** [LunarG/VulkanSamples#96]
It turns out that error when execute the command "cmake -G "Visual Studio 12 Win 64" .. as vs2015 installed until I installed vs2013. I just want to us vs2015, how to fix it?

**Comment by lenny-lunarg** [comment]
The command for Visual Studio 2015 is `cmake -G "Visual Studio 14 Win64" ..`

Version 12 or 14 denotes the version, but you use those numbers instead of the year because this is the version that visual studio uses internally. The easiest way to find the visual studio version is to go to `Help -> About Visual Studio` and look for the version. I have 14.0.25425.01 installed, but the 14 is the only part we care about. In addition, Win64 means that we want a 64-bit build. Omit that for a 32-bit build.
