### ISSUE TITLE
VK_PRESENT_MODE_FIFO_KHR should be the preferred swap mode

### ISSUE THREAD

**Issue by joedavisdev** [LunarG/VulkanSamples#98]
In API-Samples/05-init_swapchain/05-init_swapchain.cpp, VK_PRESENT_MODE_MAILBOX_KHR is used if it's available. VK_PRESENT_MODE_FIFO_KHR is more appropriate for the majority of applications as they should only render frames that will be presented to the display (the GPU shouldn't waste resources rendering images that won't be seen).

**Comment by ianelliottus** [comment]
I'm guessing that the origin of this code is from the "cube" demo, and "Example 2" of C.2.3 in the Core+WSI spec (see: https://www.khronos.org/registry/vulkan/specs/1.0-wsi_extensions/xhtml/vkspec.html#_vk_khr_swapchain).  I was involved in that, and was asked to comment here.

I'm guessing that you're coming at this from a mobile (save power by not doing unnecessary work) perspective.  True?  I'm also guessing that you are either an application developer, or somebody who works with them.  True?

For mobile applications, it is very wasteful of power to have an application that's much faster than the display's refresh rate, that doesn't throttle itself, and that uses VK_PRESENT_MODE_MAILBOX_KHR.  Is that your concern?  I can certainly see it.  I'm not sure why MAILBOX mode was recommended (the comment says it's lower-latency, which is true).

The WSI community has not given much guidance on what presentation mode to use, other than a reason why an application should use VK_PRESENT_MODE_FIFO_RELAXED_KHR.  Perhaps we can collaborate and develop some guidance.  I'll provide some ideas, and hope that my WSI buddies will join in.

First some caveats ...

I will observe that a lot of interesting applications won't have super-high frame rates relative to the display.  Some will struggle to have a new image to present with each refresh cycle.  If they can have a higher refresh rate, they will likely want to turn on more realism.

We did provide a mechanism for applications to throttle themselves.  See Example 6 in the same C.2.3 part of the spec.

Recently, I've spent some time understanding display timing needs for game and VR developers (e.g. to avoid stuttering and latency).  That's a big topic, and I'm not sure how much to share just yet.  A key point though, is that to avoid visual anomalies, it's important for the geometry for each newly-presented image to be properly placed for when that image will be displayed.

Okay, here's some thoughts on when to use each mode:

- VK_PRESENT_MODE_IMMEDIATE_KHR.  This is for applications that don't care about tearing, or have some way of synchronizing with the display (which Vulkan doesn't yet provide).
- VK_PRESENT_MODE_FIFO_KHR.  This is for applications that don't want tearing ever.  It's difficult to say how fast they may be, whether they care about stuttering/latency.
- VK_PRESENT_MODE_FIFO_RELAXED_KHR.  This is for applications that generally render/present a new frame every refresh cycle, but are occasionally late.  In this case (perhaps because of stuttering/latency concerns), they want the late image to be immediately displayed, even though that may mean some tearing.
- VK_PRESENT_MODE_MAILBOX_KHR.  I'm **guessing** that this is for applications that generally render/present a new frame every refresh cycle, but are occasionally early.  In this case, they want the new image to be displayed instead of the previously-queued-for-presentation image that has not yet been displayed.

What do you think.  Is this useful?  Should we change the cube demo, and the samples?

**Comment by joedavisdev** [comment]
Hi Ian,

True on both counts - I work in Samsung mobile's game developer ecosystem team.

My understanding is that the spec code is based on the examples in this repo. I've reported the issue here rather than against the spec as I've been told the corresponding parts are currently being re-factored.

_>Is that your concern?_
Exactly. A few developers we have supported copy + pasted from the spec, which meant their engine used MAILBOX when FIFO would have been more appropriate for both mobile and desktop. We've been able to reduce power consumption and improve frame rate in those engines by switching to FIFO. I understand there are use cases for MAILBOX, but FIFO seems like a safer place to start from.

A summary like that could be very useful for application developers. I'm not sure where the best place to put it would be though. A KHR variant of the Reference Pages could be a good fit, but it doesn't seem to exist yet.

I would vote for the demos and sample code to move to FIFO.

**Comment by Tony-LunarG** [comment]
Ok, I'll switch the demos and samples over to FIFO.  It makes the code simpler since FIFO is always guaranteed to be there, but we lose showing how to search for present modes.

**Comment by ianelliottus** [comment]
Thanks for your input Joe--it's very helpful!

> My understanding is that the spec code is based on the examples in this repo. I've reported the issue here rather than against the spec as I've been told the corresponding parts are currently being re-factored.

There's definitely been some back-and-forth, but the general flow was spec->cube->samples.  This is a good place to file it though.  However, ...

We'd like to get the cube demo to be the reference, so that we can remove the example code from the spec.  Cube gets built and used a lot, where the spec suffered bit rot until somebody filed some spec bugs:-).

> A summary like that could be very useful for application developers. I'm not sure where the best place to put it would be though. A KHR variant of the Reference Pages could be a good fit, but it doesn't seem to exist yet.

I'll bring it up with the WSI folks.

> > I would vote for the demos and sample code to move to FIFO.
> Ok, I'll switch the demos and samples over to FIFO. It makes the code simpler since FIFO is always guaranteed to be there, but we lose showing how to search for present modes.

Agreed.  Perhaps we still need a small code example in the spec?

**Comment by Tony-LunarG** [comment]
Changes to cube and samples pushed to master - anything else for this issue?
